language: node_js
node_js:
 - "8"
sudo: required
services:
 - docker

before_install:
 - docker build -t arikbidny/docker-react -f Dockerfile.dev . 

script:
 - docker run arikbidny/docker-react npm run test -- --coverage 
